### ISSUE TITLE
javadocs

### ISSUE THREAD

**Issue by larocquemb** [dlarocque/AlgorithmVisualizer#12]
code should be documented with docstrings
https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html
https://www.tutorialspoint.com/java/java_documentation.htm

**Comment by dlarocque** [comment]
Java documentation doesn't seem necessary here as this code isn't going to be used by other developers.
Added comments to help anyone who wants to understand the code or add something in the future instead.
a1ce5ef4aa31f21e450eb500131a60cf625045d0
