### ISSUE TITLE
Feature #6:  benchmark database 

### ISSUE THREAD

**Issue by larocquemb** [dlarocque/AlgorithmVisualizer#18]
would be cool if different users on different platforms could upload their performance results to a database server and the results shown here the readme, or in another html file that could be stored in the git Wiki.  

Results could be send via email to an email account dedicated for this purpose.  An application would parse the email results and store them in a database.  Then use a data visualization library like Plotly would query the database and make graphs of the different results.  

I have an 2010 Acer Inspire that is super slow and would like to compare it my new i7.  also compare with other users.

**Comment by dlarocque** [comment]
No longer possible with the removal of the sorting time. https://github.com/dlarocque/AlgorithmVisualizer/issues/35#issue-779695493
