### ISSUE TITLE
(Class name).java is a non-project file, only syntax errors are reported

### ISSUE THREAD

**Issue by dlarocque** [dlarocque/AlgorithmVisualizer#4]
Error in all .java files :
(Class name).java is a non-project file, only syntax errors are reported

Project can run, but errors are not being reported when new problems arise.

**Comment by dlarocque** [comment]
![image](https://user-images.githubusercontent.com/64338275/89596738-ac9f6580-d81d-11ea-899e-251fe810dbd0.png)

**Comment by larocquemb** [comment]
https://stackoverflow.com/questions/40831703/visual-studio-code-java-classpath-is-incomplete-only-syntax-errors-will-be-re
Install the extension: Eclipse New Java Project.
It will create the project and files needed and you won't have to worry about that classpath error. 
Then just create your class files as normal in the src folder of your new project and proceed with your programming
https://marketplace.visualstudio.com/items?itemName=mellena1.eclipse-new-java-project

alternate, better way if you really want to use VS Code. Use Maven.
https://code.visualstudio.com/docs/java/java-build

VS Code is not best IDE for Java.  Try Eclipse IDE.
https://www.eclipse.org/downloads/

**Comment by larocquemb** [comment]
VS Code is not recognizing AlgVisualiser.java as a Java source code file.  It doesn't know it should compile with java compiler.

**Comment by dlarocque** [comment]
J’ai bouger mon project a eclipse, probleme est partis.
Tu pense que c’est necessaire que je depense du temps apprendre tout a propos eclipse?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by larocquemb** [comment]
Oui, je recommande que tu apprends Eclipse pour Java.  Installe la version Entreprise Edition.  -------- Original message --------From: Daniel La Rocque <notifications@github.com>Date: Fri., Aug. 7, 2020, 8:37 p.m.To: dlarocque/AlgorithmVisualizer <AlgorithmVisualizer@noreply.github.com>Cc: Paul La Rocque <pllarocque@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [dlarocque/AlgorithmVisualizer] (Class name).java is a non-project file, only syntax errors are reported (#4)

J’ai bouger mon project a eclipse, probleme est partis.

Tu pense que c’est necessaire que je depense du temps apprendre tout a propos eclipse?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by caionfds** [comment]
> i'm using LunarVim and i get the same problem what should i do??

I'm having the same problem, can anyone help?

**Comment by RoshanAli339** [comment]
I am using my custom neovim setup and I am using the JDTLS server using LSP, and having the same issue.
Can anyone help?

**Comment by gyan-cell** [comment]
> i'm using LunarVim and i get the same problem what should i do??

i opened my bash profile in my  case  ".bashrc" and then i added " export PATH=$PATH:/usr/local/jdk/bin"  then  i restarted

for more info visit https://en.wikiversity.org/wiki/Learning_Java/Introduction_to_Java

**Comment by gyan-cell** [comment]
> i opened my bash profile in my case ".bashrc" and then i added " export PATH=$PATH:/usr/local/jdk/bin" then i restarted my terminal
> 
> "I use Arch Btw"
> 
> for more info visit https://en.wikiversity.org/wiki/Learning_Java/Introduction_to_Java



> i'm using LunarVim and i get the same problem what should i do??

**Comment by anil-nepali** [comment]
i am using vs code and same error[.java is a non-project file, only syntax errors are  reported  caused by java.lang.ClassNotFoundException!!! how to fix it

**Comment by Samar-exe** [comment]
> I am using my custom neovim setup and I am using the JDTLS server using LSP, and having the same issue.
> Can anyone help?

Did you find a solution? I use NvChad and am getting the same issue too. I'm also not being able to declare packages

**Comment by souravsgithub** [comment]
Same problem here. I am using custom neovim setup and I'm getting the same error.

**Comment by WyattBram** [comment]
Has anyone got the solution for nvim yet :(

**Comment by dlarocque** [comment]
If anyone's having issues with a neovim plugin, report those issues in the plugins' repositories.
